version: "2"

services:

  db:
    image: mysql:5.7
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    restart: unless-stopped

  app:
    build: .
    container_name: myapp
    links:
      - db
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db

  webserver:
    build: nginx
    container_name: myserver
    links:
      - app
    ports:
      - 8002:8002
    restart: unless-stopped
    depends_on:
      - app